---
title: "check"
author: "Claire Jellison"
date: "2/26/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# okay so need to account for the discrepancy btwn zip2 and campatt2 - done! they all seem to have no campaign pages
#then figure out discrepancy btwn campatt2 ad dhist2  - done! none of these seem to have donations

```{r}
nrow(zip2) - nrow(campatt2) #difference in number of camps
missingcamps <- anti_join(zip2, campatt2, by = "X")
missingcamps  #okay all of these campaigns lead to a campaign not found page so this seems fine
```

```{r}
nrow(campatt2)
dhist2check <- dhist2 %>% group_by(urlsolid) %>% summarise(donations = n())
nrow(dhist2check)
head(dhist2check)
```

```{r}
campatt2 <- campatt2 %>% rename(urlsolid = urlname) 
missingcamps2 <- anti_join(campatt2, dhist2check, by = "urlsolid")  
missingcamps2
```



#checking that it looks right below 

```{r}
nrow(dhist1)
nrow(dhist2)
dfc <- dhist1 %>% group_by(urlsolid) %>% summarise(numdonations = n_distinct(donation_id))
dfcc <- dhist2 %>% group_by(urlsolid) %>% summarise(numdonations = n_distinct(donation_id))
nrow(dfc)
nrow(dfcc)
dfc2 <- dfc %>% filter(numdonations %% 100 == 0) 
dfcc2 <- dfcc %>% filter(numdonations %% 100 == 0) 
nrow(dfc2)
nrow(dfcc2)
head(dfc2,200)

```


```{r}
pathhisttry <- "/Users/CJ/Desktop/thesisdata/p1/donationhistory.csv" 
dhisttry <- read.csv(pathhisttry)
dhisttry <- tbl_df(dhisttry)
tryatt<- "/Users/CJ/Desktop/thesisdata/p1/campattributes.csv" 
dhisttryatt <- read.csv(tryatt)
dhisttryatt <- tbl_df(dhisttryatt)
dfc <- dhisttry %>% group_by(urlsolid) %>% summarise(numdonations = n_distinct(donation_id))
nrow(dhisttryatt)
nrow(dfc)
nrow(dhisttry)
head(dfc2,200)
dfc2 <- dfc %>% filter(numdonations >= 1000) 


```



```{r}
sdp<- "/Users/CJ/Desktop/thesisdata/p1/campsbyzip1.csv" 
sdd <- read.csv(sdp)
sdd<- tbl_df(sdd)
head(sdd)
nrow(sdd)
sddf <- sdd %>% group_by(X0) %>% summarise(total = n_distinct(X)) %>% filter(total >= 20)
head(sddf)
nrow(sddf)

```
