---
title: "Untitled"
author: "Claire Jellison"
date: "12/3/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(stringr)
library(varhandle)
```


## Read in data 
```{r}
pathmerge <- "/Users/CJ/Desktop/thesisdata/sample3/donationhist.csv" 
pathzip3 <- "/Users/CJ/Desktop/thesisdata/sample3/campsbyzip1.csv" 
pathattributes <- "/Users/CJ/Desktop/thesisdata/sample3/campattributes.csv" 
compmerge <- read.csv(pathmerge)
compmerge <- tbl_df(compmerge)
zip3 <- read.csv(pathzip3)
zip3 <- tbl_df(zip3)
campattributes <- read.csv(pathattributes)
campattributes <- tbl_df(campattributes)
count(compmerge, urlsolid)

```

#Rename stuff in tables for merging 
```{r}
zip3 <- zip3 %>% 
  rename(
   urlsolid = X,
    zipcode = X0 
    )
campattributes <- campattributes[ , -1] #drop first column 
```


#Join tables on urlsolid
```{r}
fulldf <- left_join(compmerge, zip3, by = 'urlsolid') 
fulldf$is_anonymous <- str_detect(fulldf$is_anonymous, "True")
fulldf$verified <- str_detect(fulldf$verified, "True")
fulldf$is_offline <- str_detect(fulldf$is_offline, "True")
head(fulldf)
```

#Summary stats 
```{r}
mean(fulldf$amount)
median(fulldf$amount)
mean(fulldf$is_anonymous)
ggplot(data = fulldf, aes(x = amount)) + geom_bar() + xlim(0, 100) + ylim(0,250)
```

### Clean camp attributes data 

```{r}
#stuff in stringr 
#str_trim = trim leading and trailing white space 
#str_pad = pad with additional characters 
#str_detect = detects a pattern, returns TRUE/FALSE 
#str_replace = find and replace a pattern 
```


```{r}
head(campattributes)
```

```{r}
getdigits <- function(string){
  list(regmatches(string,gregexpr("[[:digit:]]+\\.*[[:digit:]]*",string)))
}

cleanattributes <- function(dfatt){ 
  dfatt$goalnum <- gsub("'raised of", "", dfatt$goalamt,
     ignore.case = FALSE)
  dfatt$goalnum <- gsub("goal'", "", dfatt$goalnum,
     ignore.case = FALSE)
  dfatt$goalamt<- gsub("[[:punct:]]", "", dfatt$goalnum,  #yo you can also use str_replace if ya want
     ignore.case = FALSE)
  dfatt$amtraised<- gsub("[[:punct:]]", "", dfatt$amtraised,
     ignore.case = FALSE)
  dfatt$goalamt <- as.integer(dfatt$goalamt)
  dfatt$amtraised <- as.integer(dfatt$amtraised)
  dfatt$terminatedbool <- str_detect(dfatt$terminated, "donations") #this doesn't work? DOUBLE CHECK
  dfatt$nonprofit <- str_detect(dfatt$nonprofit., "Registered")
  dfatt<- dfclean %>% mutate(progress = amtnum/goalnum)
}

dfclean <- cleanattributes(campattributes)
head(dfclean)
```

### time donations data 

```{r}
hmm <- fulldf  %>% select(amount, created_at, urlsolid, is_anonymous) %>% group_by(urlsolid) %>% mutate(lag1 = lag(amount,n = 1L), lag2 = lag(amount,n = 2L), lag3= lag(amount,n = 3L), lag4= lag(amount,n = 4L), lag5= lag(amount,n = 5L)) %>% mutate(alag1 = lag(is_anonymous,n = 1L), alag2 = lag(is_anonymous,n = 2L), alag3= lag(is_anonymous,n = 3L), alag4= lag(is_anonymous,n = 4L), alag5= lag(is_anonymous,n = 5L))
hmm2 <- na.omit(hmm)
hmm2$alag1 <- as.integer(as.logical(hmm2$alag1)) #switches from true false to 0/1
hmm2$alag2 <- as.integer(as.logical(hmm2$alag2))
hmm2$alag3 <- as.integer(as.logical(hmm2$alag3))
hmm2$alag4 <- as.integer(as.logical(hmm2$alag4))
hmm2$alag5 <- as.integer(as.logical(hmm2$alag5))
hmm2 <- hmm2 %>% mutate(meanonscreen = (lag1 + lag2 + lag3 + lag4 + lag5)/5) %>% mutate(anonpropscreen = (alag1 + alag2 + alag3 + alag4 + alag5)/5) 
head(hmm2)
```

#mean reg
```{r}
meanlm <- lm(amount ~ meanonscreen, data = hmm2)
summary(meanlm)
```


```{r}
anonlm <- lm(is_anonymous ~ anonpropscreen, data = hmm2)
summary(anonlm)
```



