---
title: "trees"
author: "Claire Jellison"
date: "2/8/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}


lagsort<- function(lagrow){
  a <- lagrow[1]
  b <- lagrow[2] 
  c <- lagrow[3] 
  d <- lagrow[4] 
  e <- lagrow[5]
  
  vec <- c(a,b,c,d,e)
  
  vec <- sort(vec, decreasing = FALSE) # so the are in increasing order 
  vec
}
```



```{r}
dhist2short <- dhist2 %>% ungroup(as.factor(urlsolid)) %>% select(lag1,lag2,lag3,lag4,lag5)
singlerow <- dhist2short[6,]

lagsrt <- apply(singlerow,1, lagsort) 

max <- apply(dhist2short,1,max) 
max <- as.data.frame(max)
min <- apply(dhist2short,1,min) 
min <- as.data.frame(min)
lagsrt <- apply(dhist2short,1, lagsort) 
lagsrt <- as.data.frame(lagsrt)
nrow(dhist2short)
nrow(max)
dhist2more <- cbind.data.frame(dhist2, max)
dhist2more <- cbind.data.frame(dhist2more, min)
head(dhist2more,10)
```

# algorithm 
put them in order of smallest to greatest 
a_1, a_2, a_3, a_4, a_5 
then 
compute a1 a12 a13 a14 a15 
a2 a23 a 24 a25 
a3 a34 a35 
a4 a45
a5

so function needs to put them in order and then needs to 

