---
title: "treesf.Rmd"
author: "Claire Jellison"
date: "4/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dhist10size <- read.csv("dhist10size.csv")
```

```{r}

#patition into test and training sets by full campaigns
dhist10s<- dhist10size %>% 
  group_by(urlsolid) %>% 
  summarise(tot = n())

set.seed(11)
tt <- sample(c(0,1), replace=TRUE, size=nrow(dhist10s))
dhist10s$train = tt

dhist10size <- left_join(dhist10size,dhist10s, by = "urlsolid" )
dhistrain <- dhist10size %>% dplyr::filter(train == 0)
dhistest <- dhist10size %>% dplyr::filter(train == 1)
```


```{r}
library(tree)
library(dplyr)
library(gbm)
library(randomForest)
```

```{r}
treebasic <-  tree(formula = amount ~ dispavg + is_female, data = dhistrain)
summary(treebasic)
plot(treebasic)
text(treebasic ,pretty=0)
ggsave("simpletree.png")
```

```{r}
library(rpart)
fit <- rpart(amount ~ dispavg + skewness10 + variance10 + d1,
   method="anova", data= dhistrain, 
      control=rpart.control(minsplit=1, minbucket=1, cp=0.001))
printcp(fit) # display the results

#below are parametres to mess qith 
rpart.control(minsplit = 20, minbucket = round(minsplit/3), cp = 0.01, 
      maxcompete = 4, maxsurrogate = 5, usesurrogate = 2, xval = 10,
      surrogatestyle = 0, maxdepth = 30, ...)

# plot tree
plot(fit, uniform=TRUE,
   main="Classification Tree for Kyphosis")
text(fit, use.n=TRUE, all=TRUE, cex=.8)

par(mfrow=c(1,2)) # two plots on one page
rsq.rpart(fit) # visualize cross-validation results  
```


Now to boosted tree 

```{r}
tryparams <- expand.grid(
  shrinkage = c(.001, .01, .1),
  interaction.depth = c(1, 2, 3, 4),
  n.minobsinnode = c(100, 500, 1000), #minimum number of observations in node 
  #bag.fraction = c(.65, .8, 1), 
  optimal_trees = 0,         
  min_RMSE = 0                   
)

for(i in 1:nrow(tryparams)) {
  
  gbm.tune <- gbm(
    formula = amount ~ histavg + skewness10 + kurtosis10 + variance10 + d1 + d10,
    distribution = "gaussian",
    data = dhistrain,
    n.trees = 5000,
    interaction.depth = tryparams$interaction.depth[i],
    shrinkage = tryparams$shrinkage[i],
    n.minobsinnode = tryparams$n.minobsinnode[i],
    #bag.fraction = tryparams$bag.fraction[i],
    train.fraction = .70, #use 70% of data to train the model and evaluate on the other 30% 
    n.cores = NULL, # will use all cores by default
    verbose = FALSE
  )
  
  # add min training error and trees to grid
  tryparams$optimal_trees[i] <- which.min(gbm.tune$valid.error)
  tryparams$min_RMSE[i] <- sqrt(min(gbm.tune$valid.error))
}

tryparams %>% 
  arrange(min_RMSE) 
```

```{r}
pboostree1 <- gbm(
  formula =  amount ~ histavg + skewness10 + kurtosis10 + variance10 + d1 + d10,
  distribution = "gaussian",
  data = dhistrain,
  n.trees = 173,
  interaction.depth = 3,
  shrinkage = 0.010,
  n.minobsinnode = 500,
  train.fraction = 1,
  n.cores = NULL, # will use all cores by default
  verbose = FALSE
  )  

varimpboost <- summary(pboostree1)
varimpboost %>% 
  mutate(var = fct_reorder(var, rel.inf)) %>%
  ggplot(aes(x= var, y = rel.inf)) + geom_bar(stat = "identity", color="steelblue", fill="white") +
  coord_flip() 

ya<- plot(pboostree1,i="histavg", return.grid = TRUE)
ggplot(ya, aes(x= histavg, y = y)) + geom_line() + ylim(0,500) + xlim(0,100)
```

```{r}
dhistrain<- dhistrain %>% dplyr::filter(!is.na(histavg), !is.na(skewness10), !is.na(kurtosis10), !is.na(variance10), !is.na(d1), !is.na(d10))
rftree = randomForest(amount ~ histavg + skewness10 + kurtosis10 + variance10 + d1 + d10, data= dhistrain, ntree = 30, importance =TRUE)
#na.action = na.roughfix,
varImpPlot(rftree)
plot(rftree)
#ggsave("varimprf.png", width = 7, height = 4, units = "in")
rfimp <- importance(rftree)
column = c("histavg", "is_female", "skew", "kurt", "var", "min", "max")
rfimp<- cbind(rfimp, column)

```

```{r}
regnormal <- lm(amount ~ histavg + skewness10 + kurtosis10 + variance10 + d1 + d10, data = dhistrain)
summary(regnormal)
```


predict on test data 

```{r}
dhistest <- dhistest %>% dplyr::filter(!is.na(histavg), !is.na(skewness10), !is.na(kurtosis10), !is.na(variance10), !is.na(d1), !is.na(d10))
yhatboosttest <- predict(pboostree1, newdata=dhistest, n.trees = 150)
yhatrftest <- predict(rftree, newdata=dhistest, n.trees = 40)
yhatlineartest <- predict(regnormal, newdata = dhistest)

```

```{r}
mseboost <- mean((yhatboosttest-dhistest$amount)^2)
mselinear <- mean((yhatlineartest-dhistest$amount)^2)
mserf <- mean((yhatrftest-dhistest$amount)^2)


mseboost
mselinear 
mserf
```

R^2 

```{r}
avgdonation <- mean(dhistest$amount)

ssreboost <- sum((yhatboosttest-dhistest$amount)^2)
ssrelinear <- sum((yhatlineartest-dhistest$amount)^2)
ssrerf <- sum((yhatrftest-dhistest$amount)^2)

sste <- sum((dhistest$amount-avgdonation)^2)


rlinear <- 1 - (ssrelinear/sste)
rboost <- 1 - (ssreboost/sste)
rrf <- 1 - (ssrerf/sste)


rlinear
rboost 
rrf
```

