---
title: "clean"
author: "Claire Jellison"
date: "12/27/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Here's where we clean the scraped data and write stuff to csvs


TODO: 
Do randomized test and train data (by campaign)
-- Write these to three csvs dhistrain, dhistest, dhistall


PROBLEMS: 
add no donations col (campatt)

WISHLIST: 
Add criteria for inactive campaigns (campatt)


```{r message=TRUE, warning=TRUE}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(stringr)
library(varhandle)
library(tidyr)
library(matrixStats)
library(gender)
library(lubridate)
library(fBasics)
```


#Clean zips 
```{r}
prepzip <- function(zips){

zips <- zips %>% 
  rename(
   urlsolid = X,
    zip = X0 
  ) 
zips <- zips[!duplicated(zips$urlsolid), ]
zips
} 

zips <- prepzip(zips)
```

#Clean dhist
```{r}
prepdhist <- function(dhist){ #switch to booleans, merge with zips
dhist <- left_join(dhist, zips, by = 'urlsolid') 
dhist$is_anonymous <- str_detect(dhist$is_anonymous, fixed('True', ignore_case=TRUE)) 
dhist$verified <- str_detect(dhist$verified, fixed('True', ignore_case=TRUE))
dhist$is_offline <- str_detect(dhist$is_offline, fixed('True', ignore_case=TRUE))
dhist
} 


laglead <- function(fulldf){ #add the lags and leads
fulldf <- fulldf %>% 
  group_by(urlsolid) %>%
  mutate(lag1 = dplyr::lag(amount,n = 1L), lag2 = dplyr::lag(amount,n = 2L), lag3= dplyr::lag(amount,n = 3L), lag4= dplyr::lag(amount,n = 4L), lag5= dplyr::lag(amount,n = 5L), lag6 = dplyr::lag(amount,n = 6L), lag7 = dplyr::lag(amount,n = 7L), lag8= dplyr::lag(amount,n = 8L), lag9= dplyr::lag(amount,n = 9L), lag10= dplyr::lag(amount,n = 10L), alag1 = dplyr::lag(is_anonymous,n = 1L), alag2 = dplyr::lag(is_anonymous,n = 2L), alag3= dplyr::lag(is_anonymous,n = 3L), alag4= dplyr::lag(is_anonymous,n = 4L), alag5= dplyr::lag(is_anonymous,n = 5L), alag6 = dplyr::lag(is_anonymous,n = 6L), alag7 = dplyr::lag(is_anonymous,n = 7L), alag8= dplyr::lag(is_anonymous,n = 8L), alag9= dplyr::lag(is_anonymous,n = 9L), alag10= dplyr::lag(is_anonymous,n = 10L), glag1 = dplyr::lag(is_female,n = 1L), glag2 = dplyr::lag(is_female,n = 2L), glag3= dplyr::lag(is_female,n = 3L), glag4= dplyr::lag(is_female,n = 4L), glag5= dplyr::lag(is_female,n = 5L), glag6 = dplyr::lag(is_female,n = 6L), glag7 = dplyr::lag(is_female,n = 7L), glag8= dplyr::lag(is_female,n = 8L), glag9= dplyr::lag(is_female,n = 9L), glag10= dplyr::lag(is_female,n = 10L))

fulldf <- fulldf %>% mutate(histavg = case_when(
  lagtype == "five" ~ (lag1 + lag2 + lag3 + lag4 + lag5)/5, 
  lagtype == "ten" | lagtype == "unknown" ~ (lag1 + lag2 + lag3 + lag4 + lag5 + lag6 + lag7 + lag8 + lag9 + lag10)/10)) %>%
  mutate(anonprop = case_when(
  lagtype == "five" ~ (alag1 + alag2 + alag3 + alag4 + alag5)/5, 
  lagtype == "ten" | lagtype == "unknown" ~ (alag1 + alag2 + alag3 + alag4 + alag5 + alag6 + alag7 + alag8 + alag9 + alag10)/10)) %>%
  mutate(fprop = case_when(
  lagtype == "five" ~ (glag1 + glag2 + glag3 + glag4 + glag5)/5, 
  lagtype == "ten" | lagtype == "unknown" ~ (glag1 + glag2 + glag3 + glag4 + glag5 + glag6 + glag7 + glag8 + glag9 + alag10)/10))

fulldf <- fulldf %>% select(-alag2, - alag3, - alag4, - alag5, -alag6, -alag7, -alag8, -alag9, -alag10, -glag2, - glag3, - glag4, - glag5, -glag6, -glag7, -glag8, -glag9, -glag10 )
  
fulldf 
}
#nts: had to run devtools::install_github("ropensci/genderdata") 
addgender <- function(dhist){ #add the gender based on first names by social security 
  firstname <- word(dhist$name, 1)
  firstname<- as.data.frame(firstname)
  dfull <- bind_cols(dhist, firstname)
  genderdf <- gender(as.character(dfull$firstname), method = "ssa") 
  genderdf$firstname <- genderdf$name
  genderdf <- distinct(genderdf) %>% select(-proportion_male, -proportion_female, -year_min, -year_max)
  finaldf <- left_join(dfull, genderdf, by = "firstname") 
  finaldf$is_female <- as.integer(str_detect(finaldf$gender, "female")) #get boolean for is female
  m <- finaldf$is_female
  finaldf$is_female <- coalesce(m, 0L)
  finaldf$is_anonymous <- as.integer(as.logical(finaldf$is_anonymous))
  finaldf <- finaldf %>% mutate(gender = case_when(
     is_anonymous == 1 ~ "anonymous",
    TRUE ~ gender))
  finaldf %>% select(-name.y) %>% rename(name = name.x)
}

leaddate <- function(dhist){
  dhist <- dhist  %>% 
    group_by(urlsolid) %>% 
    arrange(createdxts, .by_group = TRUE) %>%  #don't break original grouping
    mutate(createdxtslead = dplyr::lead(createdxts,n = 1L), createdxtslag = dplyr::lag(createdxts,n = 1L))
  dhist <- dhist %>% 
    mutate(timeafter = difftime(createdxtslead, createdxts, units = "secs"), timebefore = difftime(createdxts, createdxtslag, units = "secs")) #get seconds until next donation
  dhist <- dhist %>% dplyr::filter(urlsolid != "#NAME?") #like 35 of these idk why
}

fixdate <- function(date){ 
  z <- as.POSIXct(date, usetz = TRUE, format="%Y-%m-%dT%H:%M:%OS")  #look at ?strptime for documentation %Y-%m-%dT%H:%M:%S
z}

checkdateforlags <- function(dhist){  #partition data according to number of lags
  dhist <- dhist %>%
  mutate(lagtype = case_when(
    createdxts <  ymd_hms("2019-06-01 01:00:00") & createdxts > ymd_hms("2016-06-01 01:00:00")  ~ "unknown",
    createdxts <  ymd_hms("2016-06-01 01:00:00")   ~ "ten",
    createdxts >  ymd_hms("2019-06-01 01:00:00")  ~ "five"
  ))
}

sumstats <- function(f) {
  dhist10s <- f %>% dplyr::filter(lagtype == "ten" | lagtype == "unknown") %>% ungroup(urlsolid) %>% select(donation_id, lag1,lag2,lag3,lag4,lag5, lag6, lag7, lag8, lag9, lag10)
  
  variance10 <- apply(dhist10s[, 2:11], 1, var)
  skew10 <- apply(dhist10s[, 2:11], 1, skewness) #then just mutate that column otherwise 
  kurtosis10 <- apply(dhist10s[, 2:11], 1, kurtosis)
  mean10 <- apply(dhist10s[, 2:11], 1, mean)
  
  dhist10s$kurtosis10 <- kurtosis10
  dhist10s$variance10 <- variance10
  dhist10s$skewness10 <- skew10
  dhist10s$mean10 <- mean10
  
  dhist10s <- dhist10s %>% select(donation_id,kurtosis10, variance10, skewness10, mean10)
  g <- left_join(f, dhist10s, by ="donation_id")
  
  dhist5s <- f %>% dplyr::filter(lagtype == "five") %>%  ungroup(urlsolid)  %>% select(donation_id, lag1,lag2,lag3,lag4,lag5)
  
  variance5 <- apply(dhist5s[,2:6], 1, var)
  skew5 <- apply(dhist5s[,2:6], 1, skewness) 
  kurtosis5 <- apply(dhist5s[,2:6], 1, kurtosis)
  mean5 <- apply(dhist5s[,2:6], 1, mean)
  
  dhist5s$kurtosis5 <- kurtosis5
  dhist5s$variance5 <- variance5
  dhist5s$skewness5 <- skew5
  dhist5s$mean5 <- mean5
  
  dhist5s <- dhist5s %>% select(donation_id,kurtosis5, variance5, skewness5, mean5)
  
  g <- left_join(g, dhist5s, by ="donation_id")
  
  g <- g %>% mutate(kurt = coalesce(kurtosis5, kurtosis10), dispavg = coalesce(mean5, mean10), skew = coalesce(skewness5, skewness10),var = coalesce(variance5, variance10)) %>% group_by(urlsolid)
  g
}

addtimevars <- function(dhist){
  dhist <- dhist %>% mutate(createdxts = fixdate(created_at)) #get to right datetime format
  dhist <- dhist %>% mutate(dow = weekdays(createdxts)) #add day of week
  dhist <- dhist %>% mutate(month = months(createdxts)) #good
  dhist <- dhist %>% mutate(year = isoyear(createdxts)) 
  dhist <- dhist %>% mutate(hourofday = hour(createdxts))
}

maxedout <- function(dhist){#gets the number of each donor, gets camps maxed out
  a <- dhist %>% 
    group_by(urlsolid) %>% 
    summarize(countd = n()) %>% 
    mutate(maxedout = case_when(
  countd == 1000 ~ TRUE,
  TRUE ~ FALSE)) 
  dhist <- left_join(dhist, a, by = "urlsolid")
  dhist <- dhist %>% group_by(urlsolid) %>%
    mutate(numdonor = seq_len(length.out = countd)) 
  dhist
}

seed <- function(dhist){
  dhist <- dhist %>% group_by(urlsolid) %>% mutate(seedmoney= cumsum(amount) - amount)
  dhist
}


cleandhist <- function(dhist){
  dhist <- prepdhist(dhist) 
  dhist <- addtimevars(dhist)
  dhist <- leaddate(dhist) #add lead date, timeafter, timebefore, and arrange
  dhist <- checkdateforlags(dhist) 
  dhist <- addgender(dhist)
  dhist <- laglead(dhist) 
  dhist <- sumstats(dhist)
  dhist <- maxedout(dhist) 
  dhist <- seed(dhist)
}
```

```{r}
#just run this like 15 min
dhistall <- cleandhist(dhistall)

#debugging
a<- prepdhist(dhistall) #good
b<- addtimevars(a) #good
c<- leaddate(b) #good
d<- checkdateforlags(c) #good
e<- addgender(d) #good
f<- laglead(e) #good
g<- sumstats(f)#good but slow af
h<- maxedout(g) #good
i<- seed(h) #good


#divy up into train and test
m <- dhistall %>% group_by(urlsolid) %>% summarise(eh = n())
m <- m %>% select(-eh) 
set.seed(9)
split = sample(c(TRUE, FALSE), nrow(m), replace=TRUE, prob=c(0.5, 0.5))
m <- cbind(m, split)
dhistall <- left_join(dhistall, m, by = "urlsolid")

#write to csv
write.csv(dhistall,'dhistall.csv')


dhist <- cleandhist(dhist)
dhisttest <- cleandhist(dhisttest)
write.csv(dhisttest,'dhist5to8.csv')

head(f,20)

head(dhist,20)
nrow(dhist)
write.csv(g,'dhist1to4.csv')
```


### Clean campattributes 

```{r}
#stuff in stringr 
#str_trim = trim leading and trailing white space 
#str_pad = pad with additional characters 
#str_detect = detects a pattern, returns TRUE/FALSE 
#str_replace = find and replace a pattern 
```

```{r}
getdigits <- function(string){
  list(regmatches(string,gregexpr("[[:digit:]]+\\.*[[:digit:]]*",string)))
}
cleanattributes <- function(dfatt){ 
  dfatt <- dfatt[ , -1]
  dfatt$goalamt <- gsub("'raised of", "", dfatt$goalamt,
     ignore.case = FALSE)
  dfatt$goalamt <- gsub("goal'", "", dfatt$goalamt,
     ignore.case = FALSE)
  dfatt$goalamt<- gsub("[[:punct:]]", "", dfatt$goalamt,  #can also use str_replace if ya want
     ignore.case = FALSE)
  dfatt$amtraised<- gsub("[[:punct:]]", "", dfatt$amtraised,   ee5
     ignore.case = FALSE)
  dfatt$goalamt <- as.integer(dfatt$goalamt)
  dfatt$amtraised <- as.integer(dfatt$amtraised)
  dfatt$terminatedbool <- str_detect(dfatt$terminated, "donations") #double check this line
  dfatt$nonprofit <- str_detect(dfatt$nonprofit., "Registered")
  dfatt<- dfatt%>% mutate(progress = amtraised/goalamt) %>% rename(urlsolid = urlname)
}
```

```{r}
campatt <- cleanattributes(campatt)
campatt<- campatt[!duplicated(campatt$urlsolid), ]
nrow(campatt)
```

#Merge important parts of dhist and campatt

```{r}
dfc <- left_join(dhist, campatt, by = "urlsolid") 
dfc <- dfc %>% select( -description1, -description2, -description3, -nonprofit.)
```



