---
title: "clean2"
author: "Claire Jellison"
date: "3/29/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
lagsort<- function(lagrow){
  a <- lagrow[1]
  b <- lagrow[2] 
  c <- lagrow[3] 
  d <- lagrow[4] 
  e <- lagrow[5]
  vec <- c(a,b,c,d,e)
  vec <- sort(vec, decreasing = FALSE) # so the are in increasing order 
  vec
}
```

```{r}
dhist5size <- dhist5 %>% dplyr::filter(!is.na(lag1) & !is.na(lag2) &  !is.na(lag3)  & !is.na(lag4) &  !is.na(lag5))

lagsrt <- apply(dhist5size[,19:23],1, sort) 
tlagsrt <- t(lagsrt)
tlagsrt <- as.data.frame(tlagsrt)
dhist5size$d1 <- tlagsrt[,1]
dhist5size$d2 <- tlagsrt[,2]
dhist5size$d3 <- tlagsrt[,3]
dhist5size$d4 <- tlagsrt[,4]
dhist5size$d5 <- tlagsrt[,5]


dhist10size <- dhist10 %>% dplyr::filter(!is.na(lag1) & !is.na(lag2) &  !is.na(lag3)  & !is.na(lag4) &  !is.na(lag5), !is.na(lag6) & !is.na(lag7) &  !is.na(lag8)  & !is.na(lag9) &  !is.na(lag10))

lagsrt10 <- apply(dhist10size[,19:28],1, sort) 
tlagsrt10 <- t(lagsrt10)
tlagsrt10 <- as.data.frame(tlagsrt10)
dhist10size$d1 <- tlagsrt10[,1]
dhist10size$d2 <- tlagsrt10[,2]
dhist10size$d3 <- tlagsrt10[,3]
dhist10size$d4 <- tlagsrt10[,4]
dhist10size$d5 <- tlagsrt10[,5]
dhist10size$d6 <- tlagsrt10[,6]
dhist10size$d7 <- tlagsrt10[,7]
dhist10size$d8 <- tlagsrt10[,8]
dhist10size$d9 <- tlagsrt10[,9]
dhist10size$d10 <- tlagsrt10[,10]
check10 <- dhist10size %>% select(donation_id, amount, lag1, lag2, lag3, lag4, lag5, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10)

#put them in order of smallest to greatest 
#d_1, d_2, d_3, d_4, d_5 
```



```{r}

dhist10sizetest <- dhist10test %>% dplyr::filter(!is.na(lag1) & !is.na(lag2) &  !is.na(lag3)  & !is.na(lag4) &  !is.na(lag5), !is.na(lag6) & !is.na(lag7) &  !is.na(lag8)  & !is.na(lag9) &  !is.na(lag10))

lagsrt10test <- apply(dhist10sizetest[,21:30],1, sort) 
tlagsrt10test <- t(lagsrt10test)
tlagsrt10test <- as.data.frame(tlagsrt10test)
dhist10sizetest$d1 <- tlagsrt10test[,1]
dhist10sizetest$d2 <- tlagsrt10test[,2]
dhist10sizetest$d3 <- tlagsrt10test[,3]
dhist10sizetest$d4 <- tlagsrt10test[,4]
dhist10sizetest$d5 <- tlagsrt10test[,5]
dhist10sizetest$d6 <- tlagsrt10test[,6]
dhist10sizetest$d7 <- tlagsrt10test[,7]
dhist10sizetest$d8 <- tlagsrt10test[,8]
dhist10sizetest$d9 <- tlagsrt10test[,9]
dhist10sizetest$d10 <- tlagsrt10test[,10]

```
