---
title: "feregs"
author: "Claire Jellison"
date: "1/23/2020"
output: pdf_document
---

#what this website is so useful go to it 
#https://www.econometrics-with-r.org/10-3-fixed-effects-regression.html

```{r}
library(plm)
library(xts)
library(dplyr)
library(texreg)
```



```{r}
dhistfe <- dhistall %>% ungroup(urlsolid)
#dhistfe$createdxts <- make.time.unique(dhistfe$createdxts)
dhistfe$id <- seq.int(nrow(dhistfe))
dhistfe$createdxtsid  <- paste(dhistfe$createdxts, dhistfe$id, sep="_")
dhistfe5 <- dhistfe %>% dplyr::filter(lagtype == "five")
dhistpanel <- pdata.frame(dhistfe5, index = c("urlsolid", "createdxtsid"), drop.index = TRUE)
anchorfe <- plm(amount ~ histavg, 
                    data = dhistpanel, 
                    model = "within")
anchorfe2 <- plm(amount ~ histavg + is_female + histavg*is_female, 
                    data = dhistpanel, 
                    model = "within")
anchorfe3 <- plm(amount ~ histavg+ is_anonymous + histavg*is_anonymous, 
                    data = dhistpanel, 
                    model = "within")
anchorfe4 <- plm(amount ~ histavg+ nonprofit + histavg*nonprofit, 
                    data = dhistpanel, 
                    model = "within")
summary(anchorfe)
texreg(list(anchorfe, anchorfe2, anchorfe3))
```

```{r}
dhistfe10 <- dhistfe %>% dplyr::filter(lagtype == "ten")
dhistpanel10 <- pdata.frame(dhistfe10, index = c("urlsolid", "createdxtsid"), drop.index = TRUE)
anchorfe11 <- plm(amount ~ histavg, 
                    data = dhistpanel10, 
                    model = "within")
anchorfe22 <- plm(amount ~ histavg + is_female + histavg*is_female, 
                    data = dhistpanel10, 
                    model = "within")
anchorfe33 <- plm(amount ~ histavg+ is_anonymous + histavg*is_anonymous, 
                    data = dhistpanel10, 
                    model = "within")
anchorfe44 <- plm(amount ~ histavg+ nonprofit + histavg*nonprofit, 
                    data = dhistpanel10, 
                    model = "within")
texreg(list(anchorfe11, anchorfe22, anchorfe33))
```


```{r}
dhistfeinter <- dhistinter2 %>% ungroup(urlsolid)
#dhistfe$createdxts <- make.time.unique(dhistfe$createdxts)
dhistfeinter$id <- seq.int(nrow(dhistfeinter))
dhistfeinter$createdxtsid  <- paste(dhistfeinter$createdxts, dhistfeinter$id, sep="_")
dhistpanelinter <- pdata.frame(dhistfeinter, index = c("urlsolid", "createdxtsid"), drop.index = TRUE)
anchorfeinter <- plm(amount ~ histavg*lagtype + histavg*as.factor(quartile),
                    data = dhistpanelinter, 
                    model = "within")

texreg(list(anchorfeinter))
```
```


