---
title: "import"
author: "Claire Jellison"
date: "11/24/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(stringr)
```


```{r}
## Read in data 
pathhist1 <- "/Users/CJ/Desktop/thesisdata/p1/donationhistory.csv" 
pathzip1 <- "/Users/CJ/Desktop/thesisdata/p1/campsbyzip3.csv" 
pathattributes1 <- "/Users/CJ/Desktop/thesisdata/p1/campattributes.csv" 

dhist1 <- read.csv(pathhist1)
dhist1 <- tbl_df(dhist1)

zip1 <- read.csv(pathzip1)
zip1 <- tbl_df(zip1)

campatt1 <- read.csv(pathattributes1)
campatt1<- tbl_df(campatt1)
```


```{r}
## Read in data 
pathhist2 <- "/Users/CJ/Desktop/thesisdata/p2/donationhistory.csv" 
pathzip2 <- "/Users/CJ/Desktop/thesisdata/p2/campsbyzip2.csv" 
pathattributes2 <- "/Users/CJ/Desktop/thesisdata/p2/campattributes.csv" 

dhist2 <- read.csv(pathhist2)
dhist2 <- tbl_df(dhist2)

zip2 <- read.csv(pathzip2)
zip2 <- tbl_df(zip2)

campatt2 <- read.csv(pathattributes2)
campatt2<- tbl_df(campatt2)

```


```{r}
## Read in data 
pathhist3 <- "/Users/CJ/Desktop/thesisdata/p3/donationhistory.csv" 
pathzip3 <- "/Users/CJ/Desktop/thesisdata/p3/campsbyzip3.csv" 
pathattributes3 <- "/Users/CJ/Desktop/thesisdata/p3/campattributes.csv" 

dhist3 <- read.csv(pathhist3)
dhist3 <- tbl_df(dhist3)

zip3 <- read.csv(pathzip3)
zip3 <- tbl_df(zip3)

campatt3 <- read.csv(pathattributes3)
campatt3<- tbl_df(campatt3)
```

```{r}
## Read in data 

pathhist4 <- "/Users/CJ/Desktop/thesisdata/p4/donationhistory.csv" 
pathzip4 <- "/Users/CJ/Desktop/thesisdata/p4/campsbyzip4.csv" 
pathattributes4 <- "/Users/CJ/Desktop/thesisdata/p4/campattributes.csv" 

dhist4 <- read.csv(pathhist4)
dhist4 <- tbl_df(dhist4)

zip4 <- read.csv(pathzip4)
zip4 <- tbl_df(zip4)

campatt4 <- read.csv(pathattributes4)
campatt4 <- tbl_df(campatt4)
```


```{r}
## Read in data 
pathhist5 <- "/Users/CJ/Desktop/thesisdata/p5/donationhistory.csv" 
pathzip5 <- "/Users/CJ/Desktop/thesisdata/p5/campsbyzip5.csv" 
pathattributes5 <- "/Users/CJ/Desktop/thesisdata/p5/campattributes.csv" 

dhist5 <- read.csv(pathhist5)
dhist5 <- tbl_df(dhist5)

zip5 <- read.csv(pathzip5)
zip5 <- tbl_df(zip5)

campatt5 <- read.csv(pathattributes5)
campatt5 <- tbl_df(campatt5)
```


```{r}
## Read in data 
pathhist6 <- "/Users/CJ/Desktop/thesisdata/p6/donationhistory.csv" 
pathzip6 <- "/Users/CJ/Desktop/thesisdata/p6/campsbyzip6.csv" 
pathattributes6 <- "/Users/CJ/Desktop/thesisdata/p6/campattributes.csv" 

dhist6 <- read.csv(pathhist6)
dhist6 <- tbl_df(dhist6)

zip6 <- read.csv(pathzip6)
zip6 <- tbl_df(zip6)

campatt6 <- read.csv(pathattributes6)
campatt6 <- tbl_df(campatt6)

```


```{r}
## Read in data 
pathhist7 <- "/Users/CJ/Desktop/thesisdata/p7/donationhistory.csv" 
pathzip7 <- "/Users/CJ/Desktop/thesisdata/p7/campsbyzip7.csv" 
pathattributes7 <- "/Users/CJ/Desktop/thesisdata/p7/campattributes.csv" 

dhist7 <- read.csv(pathhist7)
dhist7 <- tbl_df(dhist7)

zip7 <- read.csv(pathzip7)
zip7 <- tbl_df(zip7)

campatt7 <- read.csv(pathattributes7)
campatt7 <- tbl_df(campatt7)
```

```{r}
## Read in data 

pathhist8 <- "/Users/CJ/Desktop/thesisdata/p8/donationhistory.csv" 
pathzip8 <- "/Users/CJ/Desktop/thesisdata/p8/campsbyzip8.csv" 
pathattributes8 <- "/Users/CJ/Desktop/thesisdata/p8/campattributes.csv" 

dhist8 <- read.csv(pathhist4)
dhist8 <- tbl_df(dhist4)

zip8 <- read.csv(pathzip8)
zip8 <- tbl_df(zip8)

campatt8 <- read.csv(pathattributes8)
campatt8 <- tbl_df(campatt8)
```



```{r}
#this function stacks the csvs
lapply_read_csv_bind_rows <- function(path, pattern = "*.csv") {
    files = list.files(path, pattern, full.names = TRUE)
    lapply(files, read_csv) %>% bind_rows()
}
```

```{r}
#start with time series for donations
dhist1$is_anonymous <- as.factor(dhist1$is_anonymous)
dhist1$is_offline <- as.factor(dhist1$is_offline)
dhist1$verified <- as.factor(dhist1$verified)
dhist <- bind_rows(dhist1, dhist2, dhist3, dhist4)
dhist <- dhist[!duplicated(dhist$donation_id), ]
nrow(dhist) #has 423673
#ok camp attributes time 
campatt <- bind_rows(campatt1, campatt2, campatt3, campatt4)
nrow(campatt)
#zipcodes 
zips <- bind_rows(zip1, zip2, zip3, zip4)
nrow(zips)
```

```{r}
#start with time series for donations
dhisttest <- bind_rows(dhist5, dhist6, dhist7, dhist8)
nrow(dhisttest)
dhisttest <- dhisttest[!duplicated(dhisttest$donation_id), ]
nrow(dhisttest) #has 426091
#ok camp attributes time 
campatttest <- bind_rows(campatt5, campatt6, campatt7, campatt8)
nrow(campatttest)
#zipcodes 
zipstest <- bind_rows(zip1, zip2, zip3, zip4)
nrow(zips)
```


```{r}
dhistall <- bind_rows(dhist,dhisttest)
mean(dhist$amount)
mean(dhisttest$amount)
```

