---
title: "markov"
author: "Claire Jellison"
date: "2/19/2020"
output: pdf_document
---
#YO you need to delete duplicate observations
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(vcd)
require(MASS)
```

```{r}
#https://stats.stackexchange.com/questions/76994/how-do-i-check-if-my-data-fits-an-exponential-distribution
#dhist2short <- dhist2%>% mutate(timeafter = difftime(createdxtslead, createdxts, units = "secs")) #add this to clean section
#dhist2short <- dhist2short %>% mutate(dow = weekdays(createdxts))
#dhist2short <- dhist2short %>% mutate(month = months(createdxts))

dg <- dhist %>% filter(urlsolid == "1axvo")	
ggplot(dg, aes(x=timeafter)) + geom_histogram(bins = 20) 
```

```{r}
cvec <- c(50,100, 25, 20, 10, 200, 30, 5)

dhistadd <- dhist %>% dplyr::filter(lagtype == "five") %>% mutate(rnum = goodnum(amount)) %>% distinct(donation_id, .keep_all= TRUE)

dhistadd %>% group_by(urlsolid) %>% summarize(sum(rnum), total = n()) %>% arrange(desc(total))
cands <- dhist %>% dplyr::filter(urlsolid == "keep-immigrants-diverse-in-skill-and-nationality")
head(cands,50)
nrow(cands)
```

Finding what percent of donations take on these values 

```{r}

dhistmc <- dhist %>% 
  select(amount, donation_id, urlsolid) %>% 
  mutate(niceval = case_when(
  amount %in% cvec ~ TRUE,
  TRUE ~ FALSE
))

j <- dhistmc %>% group_by(amount) %>% summarise(total = n()) %>% arrange(desc(total))
head(j,10)

head(dhistmc, 100)
summary(dhistmc$niceval)

```


```{r}
dhist[duplicated(profile_url)]
```

