---
title: "Untitled"
author: "Claire Jellison"
date: "12/3/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(stringr)
library(varhandle)
library(tidyr)
library(gender)
```
TODO: 
look at what happens when no money raised so far 
-- ah have resolved this the only problem was that the missing ones have no donations

## Read in data 
```{r}
pathhist <- "/Users/CJ/Desktop/thesisdata/sample3/donationhist.csv" 
pathzip3 <- "/Users/CJ/Desktop/thesisdata/sample3/campsbyzip1.csv" 
pathattributes <- "/Users/CJ/Desktop/thesisdata/sample3/campattributes.csv" 

dhist <- read.csv(pathhist)
dhist <- tbl_df(dhist)

zip3 <- read.csv(pathzip3)
zip3 <- tbl_df(zip3)

campattributes <- read.csv(pathattributes)
campattributes <- tbl_df(campattributes)

```

#Clean zips 
```{r}
zip3 <- zip3 %>% 
  rename(
   urlsolid = X,
    zip = X0 
    )
```

#Clean dhist
```{r}
prepdhist <- function(dhist){ #switch to booleans, merge with zips
dhist <- left_join(dhist, zip3, by = 'urlsolid') 
dhist$is_anonymous <- str_detect(dhist$is_anonymous, "True")
dhist$verified <- str_detect(dhist$verified, "True")
dhist$is_offline <- str_detect(dhist$is_offline, "True")
dhist
}

laglead <- function(fulldf){ #add the lags and leads
fulldf <- fulldf %>% group_by(as.factor(urlsolid)) %>% arrange(created_at) %>% mutate(lag1 = lag(amount,n = 1L), lag2 = lag(amount,n = 2L), lag3= lag(amount,n = 3L), lag4= lag(amount,n = 4L), lag5= lag(amount,n = 5L), alag1 = lag(is_anonymous,n = 1L), alag2 = lag(is_anonymous,n = 2L), alag3= lag(is_anonymous,n = 3L), alag4= lag(is_anonymous,n = 4L), alag5= lag(is_anonymous,n = 5L), lead1 = lead(amount,n = 1L), lead2 = lead(amount,n = 2L), lead3= lead(amount,n = 3L), lead4= lead(amount,n = 4L),lead5= lead(amount,n = 5L)) 
fulldf$alag1 <- as.integer(as.logical(fulldf$alag1)) #switches from true/false to 0/1
fulldf$alag2 <- as.integer(as.logical(fulldf$alag2))
fulldf$alag3 <- as.integer(as.logical(fulldf$alag3))
fulldf$alag4 <- as.integer(as.logical(fulldf$alag4))
fulldf$alag5 <- as.integer(as.logical(fulldf$alag5))
fulldf <- fulldf %>% mutate(histavg = (lag1 + lag2 + lag3 + lag4 + lag5)/5) %>% mutate(anonpropscreen = (alag1 + alag2 + alag3 + alag4 + alag5)/5)  %>% mutate(futavg = (lead1 + lead2 + lead3 + lead4 + lead5)/5)
fulldf }


#nts: had to run devtools::install_github("ropensci/genderdata") 
addgender <- function(dhist){ #add the gender based on first names by social security 
  firstname <- word(dhist$name, 1)
  firstname<- as.data.frame(firstname)
  dfull <- bind_cols(dhist, firstname)
  genderdf <- gender(as.character(dfull$firstname), method = "ssa") 
  genderdf$firstname <- genderdf$name
  genderdf <- distinct(genderdf) %>% select(-proportion_male, -proportion_female, -year_min, -year_max)
  finaldf <- left_join(dcheck, genderdf, by = "firstname") 
  finaldf 
  
}

```



```{r}
dhist <- prepdhist(dhist)
dhist <-laglead(dhist)
```


### Clean campattributes 

```{r}
#stuff in stringr 
#str_trim = trim leading and trailing white space 
#str_pad = pad with additional characters 
#str_detect = detects a pattern, returns TRUE/FALSE 
#str_replace = find and replace a pattern 
```

```{r}
getdigits <- function(string){
  list(regmatches(string,gregexpr("[[:digit:]]+\\.*[[:digit:]]*",string)))
}

cleanattributes <- function(dfatt){ 
  dfatt <- dfatt[ , -1]
  dfatt$goalamt <- gsub("'raised of", "", dfatt$goalamt,
     ignore.case = FALSE)
  dfatt$goalamt <- gsub("goal'", "", dfatt$goalamt,
     ignore.case = FALSE)
  dfatt$goalamt<- gsub("[[:punct:]]", "", dfatt$goalamt,  #yo you can also use str_replace if ya want
     ignore.case = FALSE)
  dfatt$amtraised<- gsub("[[:punct:]]", "", dfatt$amtraised,
     ignore.case = FALSE)
  dfatt$goalamt <- as.integer(dfatt$goalamt)
  dfatt$amtraised <- as.integer(dfatt$amtraised)
  dfatt$terminatedbool <- str_detect(dfatt$terminated, "donations") #this doesn't work? DOUBLE CHECK
  dfatt$nonprofit <- str_detect(dfatt$nonprofit., "Registered")
  dfatt<- dfatt%>% mutate(progress = amtraised/goalamt)
}


```

```{r}
campattributes <- cleanattributes(campattributes)
```







