---
title: "trees"
author: "Claire Jellison"
date: "2/8/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(fBasics)
```


```{r}
lagsort<- function(lagrow){
  a <- lagrow[1]
  b <- lagrow[2] 
  c <- lagrow[3] 
  d <- lagrow[4] 
  e <- lagrow[5]
  vec <- c(a,b,c,d,e)
  vec <- sort(vec, decreasing = FALSE) # so the are in increasing order 
  vec
}
```

```{r}
dhist5size <- dhist5 %>% dplyr::filter(!is.na(lag1) & !is.na(lag2) &  !is.na(lag3)  & !is.na(lag4) &  !is.na(lag5))

lagsrt <- apply(dhist5size[,19:23],1, sort) 
tlagsrt <- t(lagsrt)
tlagsrt <- as.data.frame(tlagsrt)
dhist5size$d1 <- tlagsrt[,1]
dhist5size$d2 <- tlagsrt[,2]
dhist5size$d3 <- tlagsrt[,3]
dhist5size$d4 <- tlagsrt[,4]
dhist5size$d5 <- tlagsrt[,5]


dhist10size <- dhist10 %>% dplyr::filter(!is.na(lag1) & !is.na(lag2) &  !is.na(lag3)  & !is.na(lag4) &  !is.na(lag5), !is.na(lag6) & !is.na(lag7) &  !is.na(lag8)  & !is.na(lag9) &  !is.na(lag10))

lagsrt10 <- apply(dhist10size[,19:28],1, sort) 
tlagsrt10 <- t(lagsrt10)
tlagsrt10 <- as.data.frame(tlagsrt10)
dhist10size$d1 <- tlagsrt10[,1]
dhist10size$d2 <- tlagsrt10[,2]
dhist10size$d3 <- tlagsrt10[,3]
dhist10size$d4 <- tlagsrt10[,4]
dhist10size$d5 <- tlagsrt10[,5]
dhist10size$d6 <- tlagsrt10[,6]
dhist10size$d7 <- tlagsrt10[,7]
dhist10size$d8 <- tlagsrt10[,8]
dhist10size$d9 <- tlagsrt10[,9]
dhist10size$d10 <- tlagsrt10[,10]
check10 <- dhist10size %>% select(donation_id, amount, lag1, lag2, lag3, lag4, lag5, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10)

#put them in order of smallest to greatest 
#d_1, d_2, d_3, d_4, d_5 
```



```{r}

dhist10sizetest <- dhist10test %>% dplyr::filter(!is.na(lag1) & !is.na(lag2) &  !is.na(lag3)  & !is.na(lag4) &  !is.na(lag5), !is.na(lag6) & !is.na(lag7) &  !is.na(lag8)  & !is.na(lag9) &  !is.na(lag10))

lagsrt10test <- apply(dhist10sizetest[,21:30],1, sort) 
tlagsrt10test <- t(lagsrt10test)
tlagsrt10test <- as.data.frame(tlagsrt10test)
dhist10sizetest$d1 <- tlagsrt10test[,1]
dhist10sizetest$d2 <- tlagsrt10test[,2]
dhist10sizetest$d3 <- tlagsrt10test[,3]
dhist10sizetest$d4 <- tlagsrt10test[,4]
dhist10sizetest$d5 <- tlagsrt10test[,5]
dhist10sizetest$d6 <- tlagsrt10test[,6]
dhist10sizetest$d7 <- tlagsrt10test[,7]
dhist10sizetest$d8 <- tlagsrt10test[,8]
dhist10sizetest$d9 <- tlagsrt10test[,9]
dhist10sizetest$d10 <- tlagsrt10test[,10]

```


now time for the basic tree model

```{r}
library(tree)
library(dplyr)
library(gbm)
library(randomForest)
```


```{r}
dhistree10 <- dhist10size %>% mutate(amount = unlist(amount))
dhistrain <- dhistree10 %>% dplyr::select(amount, skewc, varc, histavg, gender, kurtc, is_female, d1, d2,d3, d4, d5, d6, d7, d8, d9,d10)
treebasic <-  tree(formula = amount ~ histavg + skewc + kurtc + varc + is_female + d1 + d10, data = dhistrain)
summary(treebasic)
plot(treebasic)
text(treebasic ,pretty=0)
ggsave("simpletree.png")
```

Okay now for the boosted trees 
trying multiple combinations of parameters 

```{r}
tryparams <- expand.grid(
  shrinkage = c(.001, .01, .1),
  interaction.depth = c(1, 2, 3, 4),
  n.minobsinnode = c(100, 500, 1000), #minimum number of observations in node 
  #bag.fraction = c(.65, .8, 1), 
  optimal_trees = 0,         
  min_RMSE = 0                   
)
nrow(tryparams)

# can also look into changing bag.fraction
# following example of this by http://uc-r.github.io/gbm_regression

```

```{r} 
#runtime is like a couple hours for this chunk 

# iterating through parameters 
set.seed(9)

# put the rows in random order
random_index <- sample(1:nrow(dhistrain), nrow(dhistrain))
rdhistrain <- dhistrain[random_index, ]
rdhistrain <- rdhistrain %>% dplyr::filter(!is.na(is_female), !is.na(histavg), !is.na(skewc), !is.na(kurtc), !is.na(varc), !is.na(d1), !is.na(d10))

for(i in 1:nrow(tryparams)) {
  
  gbm.tune <- gbm(
    formula = amount ~ histavg + skewc + kurtc + varc + is_female + d1 + d10,
    distribution = "gaussian",
    data = rdhistrain,
    n.trees = 5000,
    interaction.depth = tryparams$interaction.depth[i],
    shrinkage = tryparams$shrinkage[i],
    n.minobsinnode = tryparams$n.minobsinnode[i],
    #bag.fraction = tryparams$bag.fraction[i],
    train.fraction = .70, #use 70% of data to train the model and evaluate on the other 30% 
    n.cores = NULL, # will use all cores by default
    verbose = FALSE
  )
  
  # add min training error and trees to grid
  tryparams$optimal_trees[i] <- which.min(gbm.tune$valid.error)
  tryparams$min_RMSE[i] <- sqrt(min(gbm.tune$valid.error))
}

tryparams %>% 
  arrange(min_RMSE) 
```


Okay now making the tree with the ideal parameters 

```{r}
pboostree1 <- gbm(
  formula = amount ~ histavg + skewc + kurtc + varc + is_female + d1 + d10,
  distribution = "gaussian",
  data = rdhistrain,
  n.trees = 158,
  interaction.depth = 2,
  shrinkage = 0.010,
  n.minobsinnode = 100,
  train.fraction = 1,
  n.cores = NULL, # will use all cores by default
  verbose = FALSE
  )  


varimpboost <- summary(pboostree1)
varimpboost %>% 
  mutate(var = fct_reorder(var, rel.inf)) %>%
  ggplot(aes(x= var, y = rel.inf)) + geom_bar(stat = "identity", color="steelblue", fill="white") +
  coord_flip() 

ggsave("relinf.png", width = 7, height = 4, units = "in")


ya<- plot(pboostree1,i="histavg", return.grid = TRUE)
ggplot(ya, aes(x= histavg, y = y)) + geom_line() + ylim(0,500) + xlim(0,1000)
yo<- plot(pboostree,i="is_female", return.grid = TRUE)
ggplot(yo, aes(x= is_female, y = y)) + geom_line()
```



Okay now for the random forest 

```{r}
rdhistrain <- na.omit(rdhistrain)
rftree = randomForest(amount ~ histavg + is_female + skewc + kurtc + varc + d1 + d10, data= rdhistrain, ntree = 100,  importance =TRUE)
#na.action = na.roughfix,
varImpPlot(rftree)
plot(rftree)
ggsave("varimprf.png", width = 7, height = 4, units = "in")
rfimp <- importance(rftree)
column = c("histavg", "is_female", "skew", "kurt", "var", "min", "max")
rfimp<- cbind(rfimp, column)

```

linear with same predictors 

```{r}
regnormal <- lm(amount ~ histavg + skewc + kurtc + varc + is_female + d1 + d10, data = dhistree)
regnormal2 <- lm(amount ~ d1 + d2 + d3 + d4 + d5 + d6 + d7 + d8 + d9 + d10 + is_female, data = dhistree)
```



#okay now predict on test data
```{r}
dhist10sizetest <- dhist10sizetest %>% dplyr::filter(!is.na(is_female), !is.na(histavg), !is.na(skewc), !is.na(kurtc), !is.na(varc), !is.na(d1), !is.na(d10))
yhat.boost.test <- predict(treeboost, newdata=dhist10sizetest, n.trees=1000)
yhat.pboost.test <- predict(pboostree1, newdata=dhist10sizetest, n.trees=158)
yhat.rf.test <- predict(rftree ,newdata=dhist10sizetest)
yhat.linear.test <- predict(regnormal, newdata = dhist10sizetest)
yhat.linear2.test <- predict(regnormal2, newdata = dhist10sizetest)
```

#mses 
```{r}
mseboost <- mean((yhat.pboost.test-dhist10sizetest$amount)^2)
mselinear <- mean((yhat.linear.test-dhist10sizetest$amount)^2)
mselinear2 <- mean((yhat.linear2.test-dhist10sizetest$amount)^2)
mserf <- mean((yhat.rf.test-dhist10sizetest$amount)^2)
avgdonation <- mean(dhist10sizetest$amount)
avgdonation

ssreboost <- sum((yhat.pboost.test-dhist10sizetest$amount)^2)
ssrelinear <- sum((yhat.linear.test-dhist10sizetest$amount)^2)
ssrerf <- sum((yhat.rf.test-dhist10sizetest$amount)^2)

sste <- sum((dhist10sizetest$amount-avgdonation)^2)

rboost <- 1 - (ssreboost/sste)
rlinear <- 1 - (ssrelinear/sste)
rrf <- 1 - (ssrerf/sste)

rboost 
rlinear 
rrf 

mselinear
#mselinear2
mseboost 
mserf
```

```{r}
#yhat.boost.test =predict(treeboost, newdata=dhist10sizetest, n.trees=1000)
#dhist10sizetest$treepred <- yhat.boost.test
#dhistree$treepred <- yhat.boost
boostreg <- lm(amount ~ yhat.boost.test, data = dhist10sizetest)
rfreg <- lm(amount ~ yhat.rf.test, data = dhist10sizetest)
regnormal <- lm(amount ~ histavg + skewc + kurtc + varc + is_female + d1 + d10, data = dhistree)
regsize <- lm(amount ~ d1 + d2 +d3 + d4 + d5 + d6 + d7 + d8 + d9 + d10, data = dhist10sizetest)
summary(boostreg)
summary(rfreg)
summary(regnormal)
summary(regsize)
texreg(regtest)
texreg(regnormal)
```

