---
title: "visuals"
author: "Claire Jellison"
date: "12/23/2019"
output: pdf_document
---

```{r}
library(ggmap)
library(zipcode)
library(maps)
library(viridis)
```

https://austinwehrwein.com/digital-humanities/creating-a-density-map-in-r-with-zipcodes/

#Now for map stuff 

```{r}
campzip <- left_join(campatt1, zip1, by = "urlsolid")
campzip$zip<- clean.zipcodes(campzip$zip)
data(zipcode)
mapdf<- merge(campzip, zipcode, by='zip')
countdf <- mapdf %>% select(urlname, zip) %>% group_by(zip) %>%  summarise(count = n_distinct(urlname))
mapdf <- left_join(mapdf, countdf, by = "zip")
```


```{r}
us<-map_data('state')

ggplot(mapdf,aes(longitude,latitude)) +
  geom_polygon(data=us,aes(x=long,y=lat,group=group),color='grey',fill=NA) +
  geom_point(aes(size= count,color = count), alpha=.25) +
  xlim(-125,-65)+ylim(23,50)
```



```{r}
dfc$zip<- clean.zipcodes(dfc$zip)
data(zipcode)
mapdf<- merge(dfc, zipcode, by='zip')
countdf <- mapdf %>% 
  select(urlsolid, donation_id, zip) %>% 
  group_by(zip) %>%  
  summarise(campaigns = n_distinct(urlsolid), donations = n_distinct(donation_id)) 
mapdf <- left_join(mapdf, countdf, by = "zip")

us<-map_data('state')

ggplot(mapdf,aes(longitude,latitude)) +
  geom_polygon(data=us,aes(x=long,y=lat,group=group),color='grey',fill=NA) +
  geom_point(aes(color = campaigns, size = donations)) +
  xlim(-125,-65) + ylim(23,50)
ggsave("map.png")
```




s


```{r}
bidf <- dhist %>% filter(urlsolid == "brianisbell")
bidf$index <- seq.int(nrow(bidf))
j = ggplot() + 
  geom_line(data = bidf, aes(x = index, y = histavg), color = "blue") + 
  geom_line(data = bidf, aes(x = index, y = amount), color = "red") + 
  geom_line(data = bidf, aes(x = index, y = futavg), color = "green") + 
  xlab('index') + 
  ylab('amount')
print(j)
```


